### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by huguei** [niclabs/dtcconfig#1]
Hi. I wonder if there's IPv6 support for the --nodes option?

> `$go run github.com/niclabs/dtcconfig rsa -t 2 -n '[2001:db8::1]:8888,[2001:db8::2]:8888' -H ...`
`Error: node ip and port format invalid. It should be ip:port`

It should be clearer in the documentation, saying explicitly "... It should be IPv4:port".

Thanks!

**Comment by eriverosr** [comment]
It was a naive mistake of our (my) part. We were splitting host and port with a colon token, now we use `url.Parse` Go builtin function to handle any valid host declared in an url-like string. Check if it works now :) 

(We changed the command that creates the config file on the new version to "create". So you need to replace  the `rsa` part on your command. Check the updated readme for more information)

**Comment by huguei** [comment]
Thanks a lot, now it works ok! :)
Just a note: you'd need to update https://github.com/niclabs/dtc/wiki/Create-Configurations too, with the change from rsa to create!
Saludos.

**Comment by eriverosr** [comment]
Done! Thanks for the tip.
